### ISSUE TITLE
Doubt on Appium drivers

### ISSUE THREAD

**Issue by Premraj1212** [automationhacks/ama#1]
Could you please explain best use cases to use UI Automator2 and Espresso for Android?
Generally we have use or pick anyone driver throughout the test or use it both together.

**Comment by automationhacks** [comment]
Hey @premraj1212.

It would be one driver for one flow, since you would have to initialize it before the test. Espresso is the latest version developed by Google and appium maintains a driver on top in [appium-espresso-driver](https://github.com/appium/appium-espresso-driver) repo. 

The wiki very apty explains the main differences:

`
The key difference between UiAutomator2 Driver and Espresso Driver is that UiAutomator2 is a black-box testing framework, and Espresso is a "grey-box" testing framework. The Espresso Driver itself is black-box (no internals of the code are exposed to the tester), but the Espresso framework itself has access to the internals of Android applications. This distinction has a few notable benefits. It can find elements that aren't rendered on the screen, it can identify elements by the Android View Tag and it makes use of IdlingResource which blocks the framework from running commands until the UI thread is free. There is limited support to automate out of app areas using the mobile command uiautomator
`

Would suggest you to explore that further. Hope this helps. Closing this issue. Feel free to re-open this or open another one in case of any further queries.
