### ISSUE TITLE
Create extension from appium

### ISSUE THREAD

**Issue by ganjarpanji** [automationhacks/ama#2]
as we know we kinda have our custom methods or actions in our test script, especially those developed for certain use cases in our app. 
i was wondering that this could possibly achievable by creating an in-house library and embed it into our test script.
do you think this is the right approach to achieve that?

**Comment by automationhacks** [comment]
Yes. Most teams create a `BasePage` class that all the different page objects inherit in order to get these actions. The `BasePage` class should contain wrappers over the library methods, this ensures that if you have to change implementation it is done in one place (SRP) and also that this logic is not spread out everywhere. Hope this helps.
